### ISSUE TITLE
Required to Merge changes on every node 

### ISSUE THREAD

**Issue by edperry** [namgk/dnr-editor#10]
I am trying to use DNR for the first time, but everytime I deploy the flow below, it requires me to merge the event on each server.

1. How do I avoid this Merging?
2. How can I run slaves as headless

I deployed the Editor on Master Node 1
And have 2 slaves. 

So I have just a basic test enviroment
I have all three nodes 

/home/eperry/node-red/node-red-dnr/

Master flow and settings port 1818
/home/eperry/node-red/node-red-dnr/flows/[settings|flow.js]

Slave Flow and settings port 1819
/home/eperry/node-red/node-red-dnr/flows-slave1/[settings|flow.js]

Slave Flow and settings port 1820
/home/eperry/node-red/node-red-dnr/flows-slave2/[settings|flow.js]

![image](https://user-images.githubusercontent.com/6684633/40245196-eba32efc-5a92-11e8-9d7b-c901677a5c34.png)

![image](https://user-images.githubusercontent.com/6684633/40244797-d6fa16b0-5a91-11e8-8723-2c8165af32f6.png)

**Comment by namgk** [comment]
Hello,

I’m not sure I understand your Merge scenario? Can you elaborate what’s
that mean? If you mean whenever there is a deploy on the master, you see a
notification on the slave’s editor, that’s totally fine and you just need
to refresh the slave’s editor. That one just means the editor recognizes
the flow has been changed in the backend and asks if you want to see the
latest flow.

For headless, since the slaves are just normal NodeRed, it’s just a simple
change in the settings file of the slaves. However they have to be
provisioned first, ie. added to the master via dnr flow import. Or else you
have to do it manually, ie. update the flow file manually without the
editor. Refer to here and search for
disableEditor
https://nodered.org/docs/configuration

**Comment by edperry** [comment]
Ah Ok so this merging is just keeping the "Browser" up to date that makes sense 

![image](https://user-images.githubusercontent.com/6684633/40251740-32b0b552-5aa8-11e8-86f7-e71515b6ef73.png)

Gotcha, YES just tested and I think that is perfect

As for editing the flow directly Ok, :( yah I can do that, could I set a Global varable in the settings.js or maybe in the ENV   instad of editing the seed node?

**Comment by namgk** [comment]
Hi,

Your slave Node-RED might have been secured by a credential, the Seed node
has to know about that in order to augment your vanilla Node-RED. That's
the reason why there is a provisioning step to configure the seed node.

Without editing that, either you cannot secure your slave with a
credential, or the step will be more complicated. What I can think of is 1)
use node-red-admin to grab an auth token from the slave Node-RED; 2) set an
ENV variable with that token so that the seed node can pick it up in order
to deploy DNR flow. Otherwise, you have to set the ENV to the actual
user/password of the slave Node-RED.

Currently these haven't been supported yet.

**Comment by edperry** [comment]
ok thanks ! just trying to be sure of what can be done. Maybe I will add that feature, Should not be too hard :)   but I am a long way off to needing that right now.

THANKS!
