### ISSUE TITLE
DNR Editor Debug (maybe feature request)

### ISSUE THREAD

**Issue by alexcarrega** [namgk/dnr-editor#11]
Is it possible to execute some flow in the dnr-editor instance?

For example, I would like to see the result in of the debug in the relative tab in the dnr-editor and not in a node-red instance of a remote (or local) device.

Thanks

**Comment by namgk** [comment]
Hi Alex,

I'm considering integrating DNR-Editor to an existing Node RED instance
without having a separate fork (through a special node). Once this is
possible, your use case will be supported. However, it requires some
engineering efforts so might not be done overnight.

In the meantime, what you can do I think is to have a separate Node-RED
instance run along side with your DNR-Editor and put a node requirement on
the debug node so that it only run on that instance. This is what I'm doing
for some of my works.

Thanks
