### ISSUE TITLE
Install nodes from dnr-editor on each instance

### ISSUE THREAD

**Issue by wrannaman** [namgk/dnr-editor#15]
For a new flow created in DNR editor that requires a new node to be installed, currently, that new module is only installed in the editor and not on each instance resulting in broken flows. 

The proposed WIP Solution: 

- When a user installs (or removes) a new module in the dnr editor, each edge instance of node red installs or removes that same module. 

@namgk Had some good thoughts:

> Deeper into the installation of node implementation, since the installation process might be complicated, such as npm build might occurs for native modules, this process is 1) lengthy, and 2) might fail. So we need to figure the strategy for this. 

> For example, if an installation is failed, should we retry it immediately? How about any back off timer till the next retry, maximum number of retries? Or simply just disable the whole flow on such device. We might need to implement some simple task queuing system for this before the full fledged flow can be up and running. 

> Further, if the missing node is device-agnostic, meaning it's computation does not depend on the device hosting it (e.g calculating maximum vs outputting current location), we also have an option to redirect the data to an external device (could be nearby) where the node is already installed and got the result back from there.

**Comment by namgk** [comment]
I managed to get a first stab on the node installation feature. Here are some updates:

DNR-Editor:

+ Node install through the editor (menu -> manage palette) won't require dependencies resolving and native building. That is, only the node's definition is fetch so that it shows up on the editor.
+ Node installation/delete events are broadcast to participating devices

Participating devices (node-red-contrib-dnr)

+ Listening for installation/delete events from the Dnr-Editor and do the installation, delete locally
+ Update the Dnr-Editor about the process (installing, installed, install_failed, deleting,...)

The next items at the editor side could be to visualise or monitor these updates from the participating devices (sort of device/installation management).

Updated node-red-contrib-dnr version: 4.1.1; dnr-editor version: 0.19.4-4.1.0

**Comment by wrannaman** [comment]
amazing! Let me try and run it now

**Comment by wrannaman** [comment]
it works!! This is amazing, thank you! We will now be rolling this out to production 🕺

**Comment by namgk** [comment]
Cheers,

Couple of notes, please see if you can integrate the installation status
for all of the device with your current device management stack.

Although it works now and it updates the status with the editor, we might
want the process to be more transparent and manageable.

One of the things is to have a force install feature I think, says 9 out of
10 devices installed correctly but the remaining one failed at some points.
If we have a dashboard kind of thing where we can see the status and force
install/retry, along with other device statuses, that’d be ideal.
