### ISSUE TITLE
Unclear on parallel execution

### ISSUE THREAD

**Issue by lucidbard** [namgk/dnr-editor#9]
Hi,

Thanks for the hard work on this, it shows a lot of promise. 

I'm trying to set up a distributed workflow which emulates gnu parallel. In order to do this, I'd like to have a single command trigger processes on multiple nodes, each routing their results back to a single node. 

Right now there seems to be no way to describe a single node as being executable by a set of devices simultaneously. Instead, I need to enumerate each device using a new node annotated with the deviceID as a constraint. I was under the impression that you could exclude the deviceID and it would send a message to all devices, but the message (say, a timestamp) doesn't arrive at every other node in spite of either 1N or NN link between them. I suspect this is because I am thinking in parallel and not as a matter of 1 message to 1 node, and that there is some intermediate node I should be using.

To reproduce, take three node-red instances, NR1, NR2 and NR3. Create a single timestamp node, an exec node (with ls as the command, excluding payload), and a debug node. Assign the timestamp node to NR1 (via node requirements) and set the exec node to a 1 1 requirement for mem/cores. Then set the debug node to N1.

Am I misunderstanding how to set up parallel flows?

**Comment by namgk** [comment]
Hi there,

Thanks for your interest. Your observation is right. It is an interesting and known limitation on the constraint definition where you cannot have an excluding constraint. I suppose adding something like "run this node on device other than X" will be something in my todo list.

The main reason behind this is when a node doesn't have a constraint, it will be deployed and available on every participating NR instances. Consequently, when the inject node realizes that there is an exec node (it's peer) that can run in the same device as its own, it won't send a message out to other devices. 

At the current situation, there is a hack to make this happen I guess. This is by using the location requirement, essentially we want all the nodes to have a constraint. So you pretending to have 3 NR instances in 3 different locations, let say the inject node is constrained to run in Vancouver, the exec to run in Seattle and the debug to run in SanFran (could be the same as Vancouver). You can do this with location-based node requirement. 

Then you configure your NR instances so that one located in Vancouver, the ones that needs to run the exec node to be located in Seattle, and the one who run the debug node to be in SanFran. You can do this by configuring the Dnr Daemon node and checking the Location Fixed checkbox.

You could try this and let me know.
